version: '3'

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:arm
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:4.2.2-1_armhf
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      #- '67:67/udp'
      - '80:80/tcp'
      #- '443:443/tcp'
    environment:
      TZ: 'America/Chicago'
      ServerIP: '127.0.0.1'
      DNS1: '10.0.0.2#54'
      DNS2: ''
      DNSMASQ_LISTENING: 'all'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './volumes/etc-pihole/:/etc/pihole/'
      - './volumes/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      - './volumes/var-log/pihole.log:/var/log/pihole.log'
      - './volumes/etc/resolv.conf:/etc/resolv.conf'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      #- 8.8.8.8
      #- 8.8.8.4
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29

